import type { Metadata } from "next";
import { Container, Section } from "@/components/ui/card";
import { MODEL_VERSION } from "@/lib/analysis/config";

export const metadata: Metadata = { title: "Methodology" };

export default function MethodologyPage() {
  return <Section><Container className="max-w-4xl"><p className="text-sm font-semibold text-[#e1cb95]">Model version {MODEL_VERSION}</p><h1 className="serif mt-2 text-4xl font-semibold">How StockBox reaches an assessment</h1><div className="mt-9 grid gap-8 text-sm leading-7 text-[#c9d2df] md:grid-cols-2"><section><h2 className="text-lg font-semibold text-[#f4efe5]">Deterministic first</h2><p className="mt-2">Provider facts retain concept, period, filing and source provenance. Missing values remain unknown, and derived values identify their source inputs.</p></section><section><h2 className="text-lg font-semibold text-[#f4efe5]">Coverage and archetypes</h2><p className="mt-2">Dimension coverage is measured against planned weights. Low coverage makes a score unavailable, while specialized company types use only economically suitable contributors.</p></section><section><h2 className="text-lg font-semibold text-[#f4efe5]">Personalized, not altered</h2><p className="mt-2">Investment profiles change dimension weights only. Summary, numbers, deep and research reports share one canonical set of facts and calculations.</p></section><section><h2 className="text-lg font-semibold text-[#f4efe5]">Model rating constraints</h2><p className="mt-2">Directional ratings require adequate score, confidence and valuation coverage. No Rating is returned when weighted coverage is insufficient.</p></section></div><p className="mt-10 border-t border-white/10 pt-6 text-xs leading-6 text-[#9aa7b8]">Static benchmarks are versioned fallbacks, not live peer comparisons. No model output is a guaranteed outcome or individualized advice.</p></Container></Section>;
}
