export const PAPER_TRADING_V3_POLICY_VERSION = "stockbox-paper-trading-v3.0.0";
export const PAPER_TRADING_V3_DEFAULT_MAX_QUOTE_AGE_MS = 20 * 60 * 1000;
export const PAPER_TRADING_V3_MAX_FUTURE_SKEW_MS = 30 * 1000;

export type PaperTradingSideV3 = "buy" | "sell";
export type PaperMarketVerificationV3 = "VERIFIED" | "UNVERIFIED" | "CONFLICT" | "UNAVAILABLE";

/**
 * Browser-originating intent. Fill price, fill timestamp, currency and provider
 * are deliberately absent: those facts must come from trusted server context.
 */
export type PaperOrderIntentV3 = {
  idempotencyKey: string;
  ticker: string;
  side: PaperTradingSideV3;
  quantity: number;
};

/** Trusted metadata generated by StockBox server code, never by the browser. */
export type TrustedPaperOrderEnvelopeV3 = {
  orderId: string;
  fillId: string;
  serverReceivedAt: string;
};

/**
 * A normalized market observation produced from StockBox's existing provider
 * chain. The paper engine never fetches or invents a market price itself.
 */
export type PaperMarketObservationV3 = {
  ticker: string;
  price: number | null;
  currency: string | null;
  observedAt: string | null;
  provider: string | null;
  verification: PaperMarketVerificationV3;
};

export type PaperCashBalanceV3 = {
  currency: string;
  amount: number;
};

export type PaperFillV3 = {
  fillId: string;
  orderId: string;
  idempotencyKey: string;
  ticker: string;
  side: PaperTradingSideV3;
  quantity: number;
  price: number;
  grossAmount: number;
  fee: number;
  currency: string;
  executedAt: string;
  marketObservedAt: string;
  provider: string;
  pricingBasis: "VERIFIED_OBSERVATION_EXACT";
  policyVersion: string;
};

export type PaperPositionV3 = {
  ticker: string;
  currency: string;
  quantity: number;
  averageCost: number;
  costBasis: number;
  realizedProfitLoss: number;
};

export type PaperTradingAccountStateV3 = {
  cash: PaperCashBalanceV3[];
  fills: PaperFillV3[];
};

export type PaperTradingRejectReasonV3 =
  | "INVALID_ORDER"
  | "DUPLICATE_IDEMPOTENCY_KEY"
  | "LEDGER_INVALID"
  | "MARKET_NOT_VERIFIED"
  | "MARKET_TICKER_MISMATCH"
  | "MARKET_PRICE_INVALID"
  | "MARKET_CURRENCY_INVALID"
  | "MARKET_TIMESTAMP_INVALID"
  | "MARKET_OBSERVATION_FUTURE"
  | "MARKET_OBSERVATION_STALE"
  | "INSUFFICIENT_CASH"
  | "INSUFFICIENT_POSITION";

export type PaperTradingExecutionV3 =
  | {
      status: "FILLED";
      fill: PaperFillV3;
      nextState: PaperTradingAccountStateV3;
      positionAfter: PaperPositionV3 | null;
    }
  | {
      status: "REJECTED";
      reason: PaperTradingRejectReasonV3;
    };

export type PaperTradingLedgerResultV3 =
  | { ok: true; positions: PaperPositionV3[] }
  | { ok: false; reason: "LEDGER_INVALID" };

function normalizedTicker(value: string | null | undefined): string | null {
  const ticker = value?.trim().toUpperCase();
  return ticker && ticker.length <= 32 ? ticker : null;
}

function normalizedCurrency(value: string | null | undefined): string | null {
  const currency = value?.trim().toUpperCase();
  return currency && /^[A-Z]{3}$/.test(currency) ? currency : null;
}

function finiteNonnegative(value: number): boolean {
  return Number.isFinite(value) && value >= 0;
}

function finitePositive(value: number): boolean {
  return Number.isFinite(value) && value > 0;
}

function nearZero(value: number): number {
  return Math.abs(value) < 1e-9 ? 0 : value;
}

function positionKey(ticker: string, currency: string): string {
  return `${ticker}|${currency}`;
}

export function derivePaperTradingLedgerV3(fills: readonly PaperFillV3[]): PaperTradingLedgerResultV3 {
  const positions = new Map<string, PaperPositionV3>();

  const ordered = [...fills].sort((left, right) => {
    const leftTime = Date.parse(left.executedAt);
    const rightTime = Date.parse(right.executedAt);
    if (leftTime !== rightTime) return leftTime - rightTime;
    return left.fillId.localeCompare(right.fillId);
  });

  for (const fill of ordered) {
    const ticker = normalizedTicker(fill.ticker);
    const currency = normalizedCurrency(fill.currency);
    const executedAt = Date.parse(fill.executedAt);
    const observedAt = Date.parse(fill.marketObservedAt);
    if (
      !ticker
      || !currency
      || !finitePositive(fill.quantity)
      || !finitePositive(fill.price)
      || !finiteNonnegative(fill.fee)
      || !Number.isFinite(executedAt)
      || !Number.isFinite(observedAt)
      || fill.grossAmount !== fill.quantity * fill.price
      || fill.pricingBasis !== "VERIFIED_OBSERVATION_EXACT"
    ) {
      return { ok: false, reason: "LEDGER_INVALID" };
    }

    const key = positionKey(ticker, currency);
    const current = positions.get(key) ?? {
      ticker,
      currency,
      quantity: 0,
      averageCost: 0,
      costBasis: 0,
      realizedProfitLoss: 0,
    };

    if (fill.side === "buy") {
      const nextQuantity = current.quantity + fill.quantity;
      const nextCostBasis = current.costBasis + fill.grossAmount + fill.fee;
      positions.set(key, {
        ...current,
        quantity: nextQuantity,
        costBasis: nextCostBasis,
        averageCost: nextQuantity > 0 ? nextCostBasis / nextQuantity : 0,
      });
      continue;
    }

    if (fill.side !== "sell" || fill.quantity > current.quantity + 1e-9) {
      return { ok: false, reason: "LEDGER_INVALID" };
    }

    const releasedCost = current.averageCost * fill.quantity;
    const nextQuantity = nearZero(current.quantity - fill.quantity);
    const nextCostBasis = nearZero(current.costBasis - releasedCost);
    positions.set(key, {
      ...current,
      quantity: nextQuantity,
      costBasis: nextCostBasis,
      averageCost: nextQuantity > 0 ? nextCostBasis / nextQuantity : 0,
      realizedProfitLoss: current.realizedProfitLoss + fill.grossAmount - fill.fee - releasedCost,
    });
  }

  return { ok: true, positions: [...positions.values()].sort((a, b) => positionKey(a.ticker, a.currency).localeCompare(positionKey(b.ticker, b.currency))) };
}

function normalizeCash(balances: readonly PaperCashBalanceV3[]): PaperCashBalanceV3[] | null {
  const merged = new Map<string, number>();
  for (const balance of balances) {
    const currency = normalizedCurrency(balance.currency);
    if (!currency || !finiteNonnegative(balance.amount)) return null;
    merged.set(currency, (merged.get(currency) ?? 0) + balance.amount);
  }
  return [...merged.entries()]
    .map(([currency, amount]) => ({ currency, amount: nearZero(amount) }))
    .sort((a, b) => a.currency.localeCompare(b.currency));
}

function setCashBalance(balances: readonly PaperCashBalanceV3[], currency: string, amount: number): PaperCashBalanceV3[] {
  const next = new Map(balances.map((balance) => [balance.currency, balance.amount]));
  next.set(currency, nearZero(amount));
  return [...next.entries()].map(([itemCurrency, itemAmount]) => ({ currency: itemCurrency, amount: itemAmount })).sort((a, b) => a.currency.localeCompare(b.currency));
}

export function executePaperMarketOrderV3(input: {
  intent: PaperOrderIntentV3;
  trusted: TrustedPaperOrderEnvelopeV3;
  market: PaperMarketObservationV3;
  state: PaperTradingAccountStateV3;
  maxQuoteAgeMs?: number;
}): PaperTradingExecutionV3 {
  const { intent, trusted, market, state } = input;
  const ticker = normalizedTicker(intent.ticker);
  const idempotencyKey = intent.idempotencyKey.trim();
  const serverTime = Date.parse(trusted.serverReceivedAt);
  const maxQuoteAgeMs = input.maxQuoteAgeMs ?? PAPER_TRADING_V3_DEFAULT_MAX_QUOTE_AGE_MS;

  if (
    !ticker
    || !idempotencyKey
    || idempotencyKey.length > 128
    || !["buy", "sell"].includes(intent.side)
    || !finitePositive(intent.quantity)
    || intent.quantity > 1_000_000_000
    || !trusted.orderId.trim()
    || !trusted.fillId.trim()
    || !Number.isFinite(serverTime)
    || !Number.isFinite(maxQuoteAgeMs)
    || maxQuoteAgeMs < 0
  ) {
    return { status: "REJECTED", reason: "INVALID_ORDER" };
  }

  if (state.fills.some((fill) => fill.idempotencyKey === idempotencyKey)) {
    return { status: "REJECTED", reason: "DUPLICATE_IDEMPOTENCY_KEY" };
  }

  const cash = normalizeCash(state.cash);
  const ledger = derivePaperTradingLedgerV3(state.fills);
  if (!cash || !ledger.ok) return { status: "REJECTED", reason: "LEDGER_INVALID" };

  if (market.verification !== "VERIFIED") return { status: "REJECTED", reason: "MARKET_NOT_VERIFIED" };
  if (normalizedTicker(market.ticker) !== ticker) return { status: "REJECTED", reason: "MARKET_TICKER_MISMATCH" };
  if (market.price === null || !finitePositive(market.price)) return { status: "REJECTED", reason: "MARKET_PRICE_INVALID" };
  const currency = normalizedCurrency(market.currency);
  if (!currency) return { status: "REJECTED", reason: "MARKET_CURRENCY_INVALID" };
  const marketTime = market.observedAt ? Date.parse(market.observedAt) : Number.NaN;
  if (!Number.isFinite(marketTime) || !market.provider?.trim()) return { status: "REJECTED", reason: "MARKET_TIMESTAMP_INVALID" };
  if (marketTime > serverTime + PAPER_TRADING_V3_MAX_FUTURE_SKEW_MS) return { status: "REJECTED", reason: "MARKET_OBSERVATION_FUTURE" };
  if (serverTime - marketTime > maxQuoteAgeMs) return { status: "REJECTED", reason: "MARKET_OBSERVATION_STALE" };

  const grossAmount = intent.quantity * market.price;
  const fee = 0;
  const currentCash = cash.find((balance) => balance.currency === currency)?.amount ?? 0;
  const currentPosition = ledger.positions.find((position) => position.ticker === ticker && position.currency === currency) ?? null;

  if (intent.side === "buy" && grossAmount + fee > currentCash + 1e-9) {
    return { status: "REJECTED", reason: "INSUFFICIENT_CASH" };
  }
  if (intent.side === "sell" && (!currentPosition || intent.quantity > currentPosition.quantity + 1e-9)) {
    return { status: "REJECTED", reason: "INSUFFICIENT_POSITION" };
  }

  const fill: PaperFillV3 = {
    fillId: trusted.fillId,
    orderId: trusted.orderId,
    idempotencyKey,
    ticker,
    side: intent.side,
    quantity: intent.quantity,
    price: market.price,
    grossAmount,
    fee,
    currency,
    executedAt: trusted.serverReceivedAt,
    marketObservedAt: market.observedAt!,
    provider: market.provider.trim(),
    pricingBasis: "VERIFIED_OBSERVATION_EXACT",
    policyVersion: PAPER_TRADING_V3_POLICY_VERSION,
  };

  const nextCashAmount = intent.side === "buy"
    ? currentCash - grossAmount - fee
    : currentCash + grossAmount - fee;
  const nextFills = [...state.fills, fill];
  const nextLedger = derivePaperTradingLedgerV3(nextFills);
  if (!nextLedger.ok) return { status: "REJECTED", reason: "LEDGER_INVALID" };

  return {
    status: "FILLED",
    fill,
    nextState: {
      cash: setCashBalance(cash, currency, nextCashAmount),
      fills: nextFills,
    },
    positionAfter: nextLedger.positions.find((position) => position.ticker === ticker && position.currency === currency) ?? null,
  };
}
