import type { Metadata } from "next";
import { ReportView } from "@/components/analysis/report-view";
import { Card, Container, Section } from "@/components/ui/card";
import { formatAnalysisTimestamp } from "@/lib/analysis/timestamp";
import { getPublicSampleAnalysis } from "@/lib/analysis/public-sample";
import { captureServerEvent } from "@/lib/analytics/events";
import { resolveCanonicalCompanySelection, searchCompanyCatalog } from "@/lib/data/company-search";
import { getLocale } from "@/lib/i18n/server";

export const metadata: Metadata = { title: "Sample Deep Analysis", description: "A real StockBox Deep Analysis snapshot showing scoring, financial metrics, confidence, missing data, deep research sections and sources.", alternates: { canonical: "/sample-analysis" } };
export const dynamic = "force-dynamic";

export default async function SampleAnalysisPage() {
  captureServerEvent("sample_analysis_view");
  const locale = await getLocale();
  const report = await getPublicSampleAnalysis();
  if (!report) return <Section><Container className="max-w-3xl"><Card><h1 className="serif text-3xl font-semibold">Sample analysis</h1><p className="mt-3 text-sm text-[#9aa7b8]">The approved sample report is temporarily unavailable. No substitute figures are generated.</p></Card></Container></Section>;
  const listingCandidates = await searchCompanyCatalog(report.ticker);
  const listing = resolveCanonicalCompanySelection({ ticker: report.ticker, canonicalTicker: report.ticker, name: report.companyName }, listingCandidates);
  const exchange = listing.ok ? listing.company.exchange : undefined;
  const sv = locale === "sv";
  return <Section><Container>
    <div className="mb-8 rounded-xl border border-[#b99b5f]/30 bg-[#b99b5f]/10 p-5">
      <p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#e1cb95]">{sv ? "Verklig Deep Analysis" : "Real Deep Analysis"}</p>
      <h1 className="serif mt-2 text-3xl font-semibold text-[#f4efe5]">{sv ? "Så här ser en riktig StockBox Deep Analysis ut" : "This is a real StockBox Deep Analysis"}</h1>
      <p className="mt-3 max-w-3xl text-sm leading-6 text-[#c9d2df]">{sv ? "Rapporten nedan är en oföränderlig AAPL-analys som StockBox faktiskt genererade i produktion. Siffror fylls inte ut för demon." : "The report below is an immutable AAPL analysis actually generated by StockBox in production. No financial figures are filled in for the demo."}</p>
      <div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-xs text-[#9aa7b8]">
        <span>{report.companyName} ? {report.ticker}{exchange ? ` ? ${exchange}` : ""}</span>
        <span>{sv ? "Analyserad" : "Analyzed"}: {formatAnalysisTimestamp(report.generatedAt, locale)}</span>
        <span>{report.modelVersion}</span><span>{report.analysisType}</span>
      </div>
    </div>
    <ReportView report={report} mode="pro" locale={locale} />
  </Container></Section>;
}
