import type { Metadata } from "next";
import Link from "next/link";
import { ReportView } from "@/components/analysis/report-view";
import { SeoJsonLd, breadcrumbJsonLd } from "@/components/seo/seo-shell";
import { Card, Container, Section } from "@/components/ui/card";
import { formatAnalysisTimestamp } from "@/lib/analysis/timestamp";
import { getPublicSampleAnalysis } from "@/lib/analysis/public-sample";
import { captureServerEvent } from "@/lib/analytics/events";

export const metadata: Metadata = {
  title: "Stock analysis example – real StockBox Deep Analysis",
  description: "See a real StockBox Deep Analysis with StockBox Score, valuation, financial metrics, confidence, missing data, risks, sources and model version.",
  alternates: {
    canonical: "/sample-analysis",
    languages: {
      "en": "/sample-analysis",
      "sv-SE": "/exempel-aktieanalys",
    },
  },
  robots: { index: true, follow: true },
  openGraph: {
    title: "Stock analysis example – real StockBox Deep Analysis",
    description: "A real StockBox research snapshot with score, fundamentals, risks, source citations and visible data limitations.",
    type: "article",
    url: "/sample-analysis",
  },
};

export const dynamic = "force-dynamic";

export default async function SampleAnalysisPage() {
  captureServerEvent("sample_analysis_view", { locale: "en", surface: "seo_example" });
  const locale = "en" as const;
  const report = await getPublicSampleAnalysis();

  if (!report) {
    return <Section><Container className="max-w-3xl"><Card><h1 className="serif text-3xl font-semibold">Stock analysis example</h1><p className="mt-3 text-sm leading-7 text-[#9aa7b8]">The approved sample report is temporarily unavailable. StockBox does not generate substitute figures to fill the demo.</p></Card></Container></Section>;
  }

  const baseUrl = process.env.NEXT_PUBLIC_APP_URL ?? "https://www.getstockbox.app";
  const pageUrl = new URL("/sample-analysis", baseUrl).toString();
  const breadcrumbs = [
    { label: "StockBox", href: "/" },
    { label: "Sample analysis", href: "/sample-analysis" },
  ];
  const structuredData = {
    "@context": "https://schema.org",
    "@graph": [
      breadcrumbJsonLd(baseUrl, breadcrumbs),
      {
        "@type": ["Article", "WebPage"],
        "@id": `${pageUrl}#sample-analysis`,
        url: pageUrl,
        headline: `Stock analysis example – ${report.companyName}`,
        description: metadata.description,
        datePublished: report.generatedAt,
        dateModified: report.generatedAt,
        inLanguage: "en",
        isAccessibleForFree: true,
        softwareVersion: report.modelVersion,
        publisher: { "@id": `${baseUrl.replace(/\/$/, "")}/#organization` },
        author: { "@id": `${baseUrl.replace(/\/$/, "")}/#organization` },
        about: { "@type": "Corporation", name: report.companyName, tickerSymbol: report.ticker },
        citation: report.sources.map((source) => source.url),
        mainEntityOfPage: pageUrl,
      },
    ],
  };

  return <>
    <SeoJsonLd data={structuredData} />
    <Section className="subtle-grid border-b border-white/10 pb-8 pt-12">
      <Container className="max-w-6xl">
        <div className="rounded-xl border border-[#b99b5f]/30 bg-[#b99b5f]/10 p-5 sm:p-7">
          <p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#e1cb95]">Real Deep Analysis</p>
          <h1 className="serif mt-2 text-3xl font-semibold text-[#f4efe5] sm:text-4xl">Stock analysis example – see a real StockBox report</h1>
          <p className="mt-3 max-w-3xl text-sm leading-7 text-[#c9d2df] sm:text-base">The report below is an immutable analysis actually generated by StockBox. Financial values are not filled in for the demo, and missing data remains missing. That makes the page a transparent example of the research output rather than a mocked marketing report.</p>
          <div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-xs text-[#9aa7b8]">
            <span>{report.companyName} · {report.ticker}</span>
            <span>Analyzed: {formatAnalysisTimestamp(report.generatedAt, locale)}</span>
            <span>Model: {report.modelVersion}</span>
            <span>Analysis type: {report.analysisType}</span>
          </div>
          <div className="mt-5 flex flex-wrap gap-x-5 gap-y-2 text-sm">
            <Link href="/docs/methodology" className="font-semibold text-[#e1cb95] hover:text-white">Methodology</Link>
            <Link href="/data-sources" className="font-semibold text-[#e1cb95] hover:text-white">Data sources</Link>
            <Link href="/research-standard" className="font-semibold text-[#e1cb95] hover:text-white">Research Standard</Link>
            <Link href="/aktier" className="font-semibold text-[#e1cb95] hover:text-white">Public stock analyses</Link>
          </div>
        </div>
      </Container>
    </Section>
    <Section className="py-8"><Container><ReportView report={report} mode="pro" locale={locale} /></Container></Section>
  </>;
}
