import "server-only";
import type { AnalysisReport } from "@/lib/analysis/types";
import { createAdminClient } from "@/lib/supabase/admin";

// Explicitly approved immutable Deep Analysis snapshot generated by StockBox in production.
export const PUBLIC_SAMPLE_ANALYSIS_ID = "913227da-7eca-4b05-981a-53f785356190";

export async function getPublicSampleAnalysis(): Promise<AnalysisReport | null> {
  const admin = createAdminClient();
  if (!admin) return null;
  const { data, error } = await admin.from("analyses").select("report").eq("id", PUBLIC_SAMPLE_ANALYSIS_ID).maybeSingle();
  if (error || !data?.report) return null;
  const report = data.report as AnalysisReport;
  if (report.id !== PUBLIC_SAMPLE_ANALYSIS_ID || report.analysisType !== "deep" || report.ticker !== "AAPL") return null;
  if (!report.historical?.financials.length || !report.historical.price.length) return null;
  const publicReport: AnalysisReport = { ...report };
  delete publicReport.adminQa;
  delete publicReport.providerDiagnostics;
  return publicReport;
}
