import type { FinancialAnalysisInput } from "../../src/lib/analysis";

export const durableCompounderInput: FinancialAnalysisInput = {
  company: {
    ticker: "BOX",
    name: "Box Systems",
    sector: "technology",
    currency: "USD",
    investmentProfile: "growth",
  },
  annualPeriods: [
    {
      fiscalYear: 2021,
      currency: "USD",
      revenue: 700,
      grossProfit: 455,
      operatingIncome: 105,
      ebitda: 126,
      netIncome: 70,
      epsDiluted: 0.7,
      operatingCashFlow: 100,
      capitalExpenditures: -20,
      cashAndEquivalents: 80,
      totalDebt: 180,
      totalEquity: 300,
      totalAssets: 600,
      currentAssets: 250,
      currentLiabilities: 160,
      interestExpense: -10,
      sharesDiluted: 100,
    },
    {
      fiscalYear: 2022,
      currency: "USD",
      revenue: 850,
      grossProfit: 561,
      operatingIncome: 153,
      ebitda: 187,
      netIncome: 102,
      epsDiluted: 1.01,
      operatingCashFlow: 145,
      capitalExpenditures: -25,
      cashAndEquivalents: 95,
      totalDebt: 190,
      totalEquity: 360,
      totalAssets: 720,
      currentAssets: 290,
      currentLiabilities: 175,
      interestExpense: -11,
      sharesDiluted: 101,
    },
    {
      fiscalYear: 2023,
      currency: "USD",
      revenue: 1000,
      grossProfit: 660,
      operatingIncome: 220,
      ebitda: 260,
      netIncome: 160,
      epsDiluted: 1.58,
      operatingCashFlow: 210,
      capitalExpenditures: -35,
      cashAndEquivalents: 120,
      totalDebt: 200,
      totalEquity: 430,
      totalAssets: 850,
      currentAssets: 340,
      currentLiabilities: 190,
      interestExpense: -12,
      sharesDiluted: 101.5,
    },
    {
      fiscalYear: 2024,
      currency: "USD",
      revenue: 1200,
      grossProfit: 840,
      operatingIncome: 312,
      ebitda: 372,
      netIncome: 240,
      epsDiluted: 2.35,
      operatingCashFlow: 320,
      capitalExpenditures: -60,
      cashAndEquivalents: 180,
      totalDebt: 220,
      totalEquity: 620,
      totalAssets: 1100,
      currentAssets: 470,
      currentLiabilities: 230,
      interestExpense: -16,
      sharesDiluted: 102,
    },
  ],
  market: {
    price: 30,
    marketCap: 3060,
    enterpriseValue: 3100,
    sharesOutstanding: 102,
    beta: 1.05,
    pricePerformance: {
      oneMonth: 0.04,
      sixMonth: 0.18,
      yearToDate: 0.22,
      oneYear: 0.38,
    },
  },
  estimates: {
    nextYearRevenueGrowth: 0.16,
    nextYearEpsGrowth: 0.18,
    nextYearFreeCashFlowGrowth: 0.14,
  },
};

export const missingDataInput: FinancialAnalysisInput = {
  company: {
    ticker: "MISS",
    name: "Missing Data Inc",
    sector: "industrials",
    currency: "USD",
    investmentProfile: "balanced",
  },
  annualPeriods: [
    {
      fiscalYear: 2023,
      currency: "USD",
      revenue: 0,
      grossProfit: 0,
      operatingIncome: -5,
      ebitda: -4,
      netIncome: -8,
      epsDiluted: -0.8,
      freeCashFlow: -12,
      totalDebt: 20,
      totalEquity: 15,
      totalAssets: 50,
    },
    {
      fiscalYear: 2024,
      currency: "USD",
      revenue: 100,
      grossProfit: 20,
      operatingIncome: -10,
      ebitda: -2,
      netIncome: -15,
      epsDiluted: -1.4,
      freeCashFlow: -30,
      cashAndEquivalents: 2,
      totalDebt: 50,
      totalEquity: 10,
      totalAssets: 70,
    },
  ],
  market: {
    price: 12,
    beta: 2.1,
  },
};
